# Generated by Django 4.1.5 on 2023-01-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptraceapi', '0003_rename_traveler_favorite_traveler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_number', models.IntegerField()),
                ('alpha2', models.CharField(max_length=10)),
                ('alpha3', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
