# Generated by Django 4.1.5 on 2023-01-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triptraceapi', '0004_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_number',
        ),
    ]
