# Generated by Django 4.1.5 on 2023-01-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triptraceapi', '0005_remove_country_country_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triptraceapi.country'),
        ),
    ]
