# Generated by Django 4.1.5 on 2023-01-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triptraceapi', '0007_rename_country_trip_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='country_id',
            new_name='country',
        ),
    ]
